### ISSUE TITLE
Completion of error handling

### ISSUE THREAD

**Issue by elfring** [eriksvedang/Carp#16]
Would you like to add more error handling for return values from functions like the following?
- [fprintf](http://pubs.opengroup.org/onlinepubs/9699919799/functions/fprintf.html "Print formatted output.") ⇒ [save_file](https://github.com/eriksvedang/Carp/blob/27e38fe037adbb0f329c74ebeda24714b8944d64/src/primops.c#L54)
- [malloc](http://pubs.opengroup.org/onlinepubs/9699919799/functions/malloc.html "Memory allocation") ⇒ [process_new](https://github.com/eriksvedang/Carp/blob/0b9c21e3323330f455343e136d4e5140171a22ca/src/process.c#L22)

**Comment by eriksvedang** [comment]
Yes definitely, error handling will be much improved when the type system allows for tagged unions (then there will be an Option type, and similar, for return values from functions like that).

**Comment by elfring** [comment]
Are you interested to apply [aspect-oriented software development](http://aspectc.org/ "AspectC++")?
How do you think about to encapsulate error detection and corresponding exception handling as [a reusable aspect](https://en.wikipedia.org/wiki/Aspect_%28computer_programming%29 "Combination of a pointcut with advice") in your software?

**Comment by eriksvedang** [comment]
I don't know very much about aspect-oriented programming. Currently I have no plans to incorporate that into Carp.

**Comment by elfring** [comment]
I suggest to avoid [ignorance of return values](https://cwe.mitre.org/data/definitions/252.html "Unchecked return values") a bit more. How do you think about to improve [static source code analysis](https://en.wikipedia.org/wiki/List_of_tools_for_static_code_analysis#C.2C_C.2B.2B "Tools for static code analysis") also for your software?

Do you find information sources like the following useful?
* Article "[A Reusable Aspect for Memory Allocation Checking](https://web.archive.org/web/20120220075303/http://research.msrg.utoronto.ca/ACC/Tutorial#A_Reusable_Aspect_for_Memory_All "AspectC Tutorial")"
* Document "[Aspect-Oriented Software Development - An Introduction](https://web.archive.org/web/20130512025224/http://www.info.ucl.ac.be/~jbrichau/courses/introductionToAOSD.pdf "AOSD")" by Johan Brichau and Theo D'Hondt
* Paper "[On Typesafe Aspect Implementations in C++](http://citeseerx.ist.psu.edu/viewdoc/summary?doi=10.1.1.125.2164 "AspectC++")" by Daniel Lohmann and Olaf Spinczyk

**Comment by bagucode** [comment]
Thank you for the insightful comments and useful links @elfring!
Reliability and security are definitively important to consider when making any software and in particular "platform software" such as an operating system, compiler or standard library for a programming language.
However, I must say that I think aspect oriented programming is a very bad thing. It attempts to be an ultimate solution to a whole category of issues. Sadly, as many such things go, in the end it turns out to cause more problems than it solves because it introduces non-local effects and may unexpectedly alter program behaviour when there are subtle errors in the aspect or it is applied in a place where the programmer did not expect when introducing the aspect. For real performance and reliability, each code path must be considered in its context and be purposefully designed. I do not think there are any shortcuts that are worthwhile in the end.

**Comment by elfring** [comment]
>However, I must say that I think aspect oriented programming is a very bad thing.

I am surprised by such a view. I understand your concerns to some degree.
How are the chances that a better understanding can be achieved for the suggested software development methodologies?
